// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd_6TYRG-LbkDwRQAwxrfPahQPi17DKdE',
    appId: '1:1065782059336:web:a56abe0d0136d44a5f537d',
    messagingSenderId: '1065782059336',
    projectId: 'ecommerceapp-125e1',
    authDomain: 'ecommerceapp-125e1.firebaseapp.com',
    storageBucket: 'ecommerceapp-125e1.firebasestorage.app',
    measurementId: 'G-FMJWETJGH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJRlfu8wzA1YpAnLtAy2J8170Td2GDAPk',
    appId: '1:1065782059336:android:404668499320051e5f537d',
    messagingSenderId: '1065782059336',
    projectId: 'ecommerceapp-125e1',
    storageBucket: 'ecommerceapp-125e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGQafvfEAjT9x17SVQd3lW52ylpUdemqY',
    appId: '1:1065782059336:ios:3e1a91fe045465995f537d',
    messagingSenderId: '1065782059336',
    projectId: 'ecommerceapp-125e1',
    storageBucket: 'ecommerceapp-125e1.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGQafvfEAjT9x17SVQd3lW52ylpUdemqY',
    appId: '1:1065782059336:ios:3e1a91fe045465995f537d',
    messagingSenderId: '1065782059336',
    projectId: 'ecommerceapp-125e1',
    storageBucket: 'ecommerceapp-125e1.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCd_6TYRG-LbkDwRQAwxrfPahQPi17DKdE',
    appId: '1:1065782059336:web:489078c32db9c7475f537d',
    messagingSenderId: '1065782059336',
    projectId: 'ecommerceapp-125e1',
    authDomain: 'ecommerceapp-125e1.firebaseapp.com',
    storageBucket: 'ecommerceapp-125e1.firebasestorage.app',
    measurementId: 'G-LSTY2406LR',
  );
}
